version: "3.3"
services:
  backend:
    build: ./go
    tty: true
    ports:
      - "8083:80"

  mysql:
    build: ./mysql
    ports:
      - "33060:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: todo
      MYSQL_USER: gopher
      MYSQL_PASSWORD: gopher-pw
