swagger: '2.0'
info:
  version: "1.1"
  title: ' '
  description: 'todo'



paths:
  /task:
    post:
      tags:
      - "task"
      summary: "内容と期限を受け取る"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema: 
            type: "object"
            properties:
              detail:
                type: "string"
                format: "string"
              deadline:
                type: "string"
                format: "yyyy-mm-dd"
      responses:
        200:
          description: 'response'
          schema: 
            type: 'object'
            properties:
              message:
                type: 'string'
                format: 'register complete'

    put:
      tags:
      - 'task'
      summary: "達成済みにする"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          description: 'response'
          schema: 
            type: 'object'
            properties:
              taskID:
                type: integer
      responses:
        200:
          description: OK
          schema: 
              type: 'object'
              properties:
                message:
                  type: 'string'

    get:
      tags:
        - 'task'
      summary: "タスク一覧を返す"
      produces:
        - "application/json"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: "object"
              properties:
                taskID: 
                  type: "integer"
                date:
                  type: "string"
                detail:
                  type: "string"
                deadline:
                  type: "string"
